import { defineConfig } from "oxfmt";

export default defineConfig({
  endOfLine: "lf",
  semi: true,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  printWidth: 100,
  sortPackageJson: {
    sortScripts: true,
  },
  sortImports: {
    groups: [
      "type-import",
      ["value-builtin", "value-external"],
      "type-internal",
      "value-internal",
      ["type-parent", "type-sibling", "type-index"],
      ["value-parent", "value-sibling", "value-index"],
      "unknown",
    ],
  },
  sortTailwindcss: {
    stylesheet: "src/styles.css",
    functions: ["clsx", "cn", "cva"],
  },
  ignorePatterns: [
    "build",
    "logs",
    "*.log",
    "npm-debug.log*",
    "yarn-debug.log*",
    "yarn-error.log*",
    "lerna-debug.log*",
    ".pnpm-debug.log*",
    "report.[0-9]*.[0-9]*.[0-9]*.[0-9]*.json",
    "pids",
    "*.pid",
    "*.seed",
    "*.pid.lock",
    "lib-cov",
    "coverage",
    "*.lcov",
    ".nyc_output",
    ".grunt",
    "bower_components",
    ".lock-wscript",
    "build/Release",
    "node_modules/",
    "jspm_packages/",
    "web_modules/",
    "*.tsbuildinfo",
    ".npm",
    ".eslintcache",
    ".stylelintcache",
    ".rpt2_cache/",
    ".rts2_cache_cjs/",
    ".rts2_cache_es/",
    ".rts2_cache_umd/",
    ".node_repl_history",
    "*.tgz",
    ".yarn-integrity",
    ".env",
    ".env.development.local",
    ".env.test.local",
    ".env.production.local",
    ".env.local",
    ".cache",
    ".parcel-cache",
    ".next",
    "out",
    ".nuxt",
    "dist",
    ".cache/",
    ".vuepress/dist",
    ".temp",
    ".docusaurus",
    ".serverless/",
    ".fusebox/",
    ".dynamodb/",
    ".tern-port",
    ".vscode-test",
    ".yarn/cache",
    ".yarn/unplugged",
    ".yarn/build-state.yml",
    ".yarn/install-state.gz",
    ".pnp.*",
    "routeTree.gen.ts",
  ],
});
