/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacksIndexRouteImport } from './routes/packs/index'
import { Route as MixerIndexRouteImport } from './routes/mixer/index'
import { Route as PacksPackIdRouteImport } from './routes/packs/$packId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksIndexRoute = PacksIndexRouteImport.update({
  id: '/packs/',
  path: '/packs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MixerIndexRoute = MixerIndexRouteImport.update({
  id: '/mixer/',
  path: '/mixer/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacksPackIdRoute = PacksPackIdRouteImport.update({
  id: '/packs/$packId',
  path: '/packs/$packId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/mixer': typeof MixerIndexRoute
  '/packs': typeof PacksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/mixer': typeof MixerIndexRoute
  '/packs': typeof PacksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/packs/$packId': typeof PacksPackIdRoute
  '/mixer/': typeof MixerIndexRoute
  '/packs/': typeof PacksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/packs/$packId' | '/mixer' | '/packs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/packs/$packId' | '/mixer' | '/packs'
  id: '__root__' | '/' | '/about' | '/packs/$packId' | '/mixer/' | '/packs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PacksPackIdRoute: typeof PacksPackIdRoute
  MixerIndexRoute: typeof MixerIndexRoute
  PacksIndexRoute: typeof PacksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/': {
      id: '/packs/'
      path: '/packs'
      fullPath: '/packs'
      preLoaderRoute: typeof PacksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mixer/': {
      id: '/mixer/'
      path: '/mixer'
      fullPath: '/mixer'
      preLoaderRoute: typeof MixerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packs/$packId': {
      id: '/packs/$packId'
      path: '/packs/$packId'
      fullPath: '/packs/$packId'
      preLoaderRoute: typeof PacksPackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PacksPackIdRoute: PacksPackIdRoute,
  MixerIndexRoute: MixerIndexRoute,
  PacksIndexRoute: PacksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
